"""make raw_llm_response nullable

Revision ID: 000adf5e1a4e
Revises: 106f16b3f067
Create Date: 2026-08-20 21:50:41.845299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000adf5e1a4e'
down_revision: Union[str, None] = '106f16b3f067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pre_visit_summaries', 'raw_llm_response',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pre_visit_summaries', 'raw_llm_response',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
