"""add google_refresh_token to users

Revision ID: 1a4a7f3572f4
Revises: 9e82f0dfc456
Create Date: 2026-08-20 22:35:46.577791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4a7f3572f4'
down_revision: Union[str, None] = '9e82f0dfc456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_refresh_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_refresh_token')
    # ### end Alembic commands ###
