"""add is_active to users

Revision ID: 4c8921a1cea7
Revises: 0001
Create Date: 2026-08-20 21:29:04.060320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8921a1cea7'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_post_visit_summary_appointment', 'post_visit_summaries', type_='unique')
    op.drop_index('ix_post_visit_summaries_appointment_id', table_name='post_visit_summaries')
    op.create_index(op.f('ix_post_visit_summaries_appointment_id'), 'post_visit_summaries', ['appointment_id'], unique=True)
    op.drop_constraint('uq_pre_visit_summary_appointment', 'pre_visit_summaries', type_='unique')
    op.drop_index('ix_pre_visit_summaries_appointment_id', table_name='pre_visit_summaries')
    op.create_index(op.f('ix_pre_visit_summaries_appointment_id'), 'pre_visit_summaries', ['appointment_id'], unique=True)
    op.drop_constraint('uq_symptom_form_appointment', 'symptom_forms', type_='unique')
    op.drop_index('ix_symptom_forms_appointment_id', table_name='symptom_forms')
    op.create_index(op.f('ix_symptom_forms_appointment_id'), 'symptom_forms', ['appointment_id'], unique=True)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_symptom_forms_appointment_id'), table_name='symptom_forms')
    op.create_index('ix_symptom_forms_appointment_id', 'symptom_forms', ['appointment_id'], unique=False)
    op.create_unique_constraint('uq_symptom_form_appointment', 'symptom_forms', ['appointment_id'])
    op.drop_index(op.f('ix_pre_visit_summaries_appointment_id'), table_name='pre_visit_summaries')
    op.create_index('ix_pre_visit_summaries_appointment_id', 'pre_visit_summaries', ['appointment_id'], unique=False)
    op.create_unique_constraint('uq_pre_visit_summary_appointment', 'pre_visit_summaries', ['appointment_id'])
    op.drop_index(op.f('ix_post_visit_summaries_appointment_id'), table_name='post_visit_summaries')
    op.create_index('ix_post_visit_summaries_appointment_id', 'post_visit_summaries', ['appointment_id'], unique=False)
    op.create_unique_constraint('uq_post_visit_summary_appointment', 'post_visit_summaries', ['appointment_id'])
    # ### end Alembic commands ###
