"""add retry columns to notifications_log

Revision ID: 9e82f0dfc456
Revises: 000adf5e1a4e
Create Date: 2026-08-20 22:14:57.351152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e82f0dfc456'
down_revision: Union[str, None] = '000adf5e1a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_log', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('notifications_log', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications_log', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications_log', 'error_message')
    op.drop_column('notifications_log', 'next_retry_at')
    op.drop_column('notifications_log', 'retry_count')
    # ### end Alembic commands ###
